# Generated by Django 6.1.1 on 2026-09-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EntrepriseApp", "0001_initial"),
        ("ExpeditionApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delai_jours", models.IntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("proposee", "Proposée"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("retiree", "Retirée"),
                        ],
                        default="proposee",
                        max_length=20,
                    ),
                ),
                ("date_proposition", models.DateField(auto_now_add=True)),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ExpeditionApp.expedition",
                    ),
                ),
                (
                    "transporteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EntrepriseApp.entreprise",
                    ),
                ),
            ],
        ),
    ]
