# Generated by Django 6.1.1 on 2026-10-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OffreApp", "0002_initial"),
        ("VehiculeApp", "0002_alter_vehicule_capacite_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offre",
            name="vehicule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="VehiculeApp.vehicule",
            ),
            preserve_default=False,
        ),
    ]
