# Generated by Django 6.1.1 on 2026-10-06 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EntrepriseApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="adresse",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, "L'adresse doit contenir au moins 20 caractères."
                    ),
                    django.core.validators.MaxLengthValidator(
                        400, "L'adresse ne peut pas dépasser 400 caractères."
                    ),
                ]
            ),
        ),
    ]
