# Generated by Django 6.1.1 on 2026-10-06 15:16

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EntrepriseApp", "0002_alter_entreprise_adresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="matricule_fiscale",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format du matricule fiscal invalide.",
                        regex="^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[EntrepriseApp.models.validate_email],
            ),
        ),
    ]
