# Generated by Django 6.1.1 on 2026-09-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EntrepriseApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immatriculation", models.CharField(max_length=20, unique=True)),
                (
                    "type_vehicule",
                    models.CharField(
                        choices=[
                            ("camionnette,", "camionnette,"),
                            ("camion porteur,", "camion porteur,"),
                            ("semi-remorque", "semi-remorque"),
                            ("fourgon", "Fourgon"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacite_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to="EntrepriseApp.entreprise",
                    ),
                ),
            ],
        ),
    ]
